### ISSUE TITLE
Peer to peer code review.

### ISSUE THREAD

**Issue by Muhammad0602** [NicolasAndrehh/To-Do-List#4]
Great job @NicolasAndrehh on doing this great job. Your project looks perfect but still, there is room for improvement. Kindly consider the following suggestions. 
- change the default functionality of your completed attribute in local storage. 
- add some css to your li, so it looks better when it is in focus mode.

**Comment by NicolasAndrehh** [comment]
Thank you, the issue is already solved👍.
